---
name: Publish Docker image

on:
  push:

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 30000
          # It takes some time to delete files and I don't
          # think it is necessary right now
          # remove-dotnet: 'true'
          # remove-android: 'true'
          # remove-haskell: 'true'
          # remove-codeql: 'true'

      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Read base tag
        id: read_base_tag
        run: |
            echo BASE_TAG is `cat BASE_TAG`
            echo BASE_TAG=`cat BASE_TAG` >> $GITHUB_OUTPUT

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: iavas/runpod-pytorch
          flavor: latest=true
          tags: ${{ steps.read_base_tag.outputs.BASE_TAG }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Uncomment for a fancy terminal
      # - name: Setup upterm session
      # uses: lhotari/action-upterm@v1

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v5
        with:
          build-args: BASE_TAG=${{ steps.read_base_tag.outputs.BASE_TAG }}
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
